[functions."scheduledEmailCheck"]
    schedule = "@hourly"

[build]
    publish = "public"
    functions = "functions"

[dev]
  framework = "#static"
  publish = "public"
  functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200